baseURL = "/"
title = "Komapper"

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "Komapper"
description = "Kotlin ORM for JDBC and R2DBC"
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.ja]
description = "JDBC と R2DBC のための Kotlin ORM"
languageName ="Japanese"
contentDir = "content/ja"
#time_format_default = "2006.02.01"
#time_format_blog = "2006.02.01"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML"]

[params]
copyright = "The Komapper Authors"
# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
images = ["https://www.komapper.org/background.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = true #can_be_replaced_with_gradle

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "v1.13" #can_be_replaced_with_gradle

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://www.komapper.org/"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/komapper/komapper.github.io"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/komapper/komapper"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch = "v1.13" #can_be_replaced_with_gradle

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "c4b340a784facde3d"

# Enable Algolia DocSearch
algolia_docsearch = false #can_be_replaced_with_gradle

# Enable Lunr.js offline search
offlineSearch = true #can_be_replaced_with_gradle

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# Add your release versions here
#[[params.versions]]
#version = "latest"
#url = "https://www.komapper.org/"
[[params.versions]]
version = "latest"
url = "https://www.komapper.org/"
[[params.versions]]
version = "v1.13"
url = "https://v1-13.komapper.org/"
[[params.versions]]
version = "v1.12"
url = "https://v1-12.komapper.org/"
[[params.versions]]
version = "v1.11"
url = "https://v1-11.komapper.org/"
[[params.versions]]
version = "v1.10"
url = "https://v1-10.komapper.org/"
[[params.versions]]
version = "v1.9"
url = "https://v1-9.komapper.org/"
[[params.versions]]
version = "v1.8"
url = "https://v1-8.komapper.org/"
[[params.versions]]
version = "v1.7"
url = "https://v1-7.komapper.org/"
[[params.versions]]
version = "v1.6"
url = "https://v1-6.komapper.org/"
[[params.versions]]
version = "v1.5"
url = "https://v1-5.komapper.org/"
[[params.versions]]
version = "v1.4"
url = "https://v1-4.komapper.org/"
[[params.versions]]
version = "v1.3"
url = "https://v1-3.komapper.org/"
[[params.versions]]
version = "v1.2"
url = "https://v1-2.komapper.org/"
[[params.versions]]
version = "v1.1"
url = "https://v1-1.komapper.org/"
[[params.versions]]
version = "v1.0"
url = "https://v1-0.komapper.org/"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/komapper/komapper.github.io/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/komapper/komapper.github.io/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
#[[params.links.user]]
#	name = "User mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
#        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name = "GitHub"
	url = "https://github.com/komapper/komapper"
	icon = "fab fa-github"
		desc = "Development takes place here!"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/komapper"
	icon = "fab fa-twitter"
		desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Slack"
	url = "https://kotlinlang.slack.com/messages/komapper/"
	icon = "fab fa-slack"
		desc = "Chat with other project developers"
#[[params.links.user]]
#	name = "Stack Overflow"
#	url = "https://example.org/stack"
#	icon = "fab fa-stack-overflow"
#        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
#[[params.links.developer]]
#	name = "Developer mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
#        desc = "Discuss development issues around the project"

# hugo module configuration

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.75.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false